FROM node:14-slim

RUN  npm install -g nodemon
# Step 4.1 - Add container working directory

LABEL maintainer student

WORKDIR /app


COPY package.json .

RUN npm install
# Step 4.2 - Copy npm dependencies

# Step 4.3 - Install dependencies

# Copy app source code

COPY . .

#Expose port and start application

EXPOSE 3260

CMD ["npm", "run", "dev"]